settings:
  title: 'SSUG Status'
  url: 'https://status.ssug.top' # used for Slack messages
  logo: SSUG.jpeg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: ssug-website # unique identifier
    name: SSUG Website
    description: 'The SSUG Official Website' # default=empty
    url: 'https://ssug.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: ssug-central-matrix-server # unique identifier
    name: SSUG Central Matrix Server
    description: 'The SSUG Central Matrix Server' # default=empty
    url: 'https://matrix.ssug.top/_matrix/static/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

