settings:
  title: 'SSUG Status'
  url: 'https://status.ssug.top' # used for Slack messages
  logo: SSUG.jpeg # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: ssug-website # unique identifier
    name: SSUG Website
    description: 'The SSUG Official Website' # default=empty
    url: 'https://www.ssug.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: ssug-central-matrix-server # unique identifier
    name: SSUG Central Matrix Server
    description: 'The SSUG Central Matrix Server' # default=empty
    url: 'https://matrix.ssug.top/_matrix/static/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: ssug-element-web # unique identifier
    name: SSUG Element Web
    description: 'The SSUG Element Web Client' # default=empty
    url: 'https://element.ssug.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: ssug-sso-front_end # unique identifier
    name: SSUG SSO Service (Front-end)
    description: 'The Front-end of SSUG SSO Service' # default=empty
    url: 'https://sso.ssug.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: ssug-sso-back-end # unique identifier
    name: SSUG SSO Service (Back-end)
    description: 'The Back-end of SSUG SSO Service' # default=empty
    url: 'https://api.sso.ssug.top/status_check' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: ssug-law # unique identifier
    name: SSUG Laws Database
    description: 'The SSUG Laws Database' # default=empty
    url: 'https://law.ssug.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: ssug-sso-oauth # unique identifier
    name: SSUG SSO Service (OAuth)
    description: 'The OAuth Part of SSUG SSO Service' # default=empty
    url: 'https://oauth.ssug.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true    

  - id: ssug-nav # unique identifier
    name: SSUG Homepage # follow the website's title
    description: 'The SSUG Official Navigation Website' # default=empty
    url: 'https://nav.ssug.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true    

  - id: ssug-ai # unique identifier
    name: SSUG AI Service (OpenWebUI)
    description: 'The SSUG Official AI Model Provider Based on OpenWebUI' # default=empty
    url: 'https://ai.ssug.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true    

  - id: ssug-fatpaper # unique identifier
    name: SSUG Fatpaper Game
    description: 'The SSUG Official Game Website' # default=empty
    url: 'http://fatpaper.game.ssug.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true    
